using Dalamud.Game.Text;

namespace clib.Extensions;

public static class CharExtensions {
    public static char ReplaceSeIconLetters(this char seIconChar) => seIconChar switch {
        (char)SeIconChar.BoxedLetterA => 'A',
        (char)SeIconChar.BoxedLetterB => 'B',
        (char)SeIconChar.BoxedLetterC => 'C',
        (char)SeIconChar.BoxedLetterD => 'D',
        (char)SeIconChar.BoxedLetterE => 'E',
        (char)SeIconChar.BoxedLetterF => 'F',
        (char)SeIconChar.BoxedLetterG => 'G',
        (char)SeIconChar.BoxedLetterH => 'H',
        (char)SeIconChar.BoxedLetterI => 'I',
        (char)SeIconChar.BoxedLetterJ => 'J',
        (char)SeIconChar.BoxedLetterK => 'K',
        (char)SeIconChar.BoxedLetterL => 'L',
        (char)SeIconChar.BoxedLetterM => 'M',
        (char)SeIconChar.BoxedLetterN => 'N',
        (char)SeIconChar.BoxedLetterO => 'O',
        (char)SeIconChar.BoxedLetterP => 'P',
        (char)SeIconChar.BoxedLetterQ => 'Q',
        (char)SeIconChar.BoxedLetterR => 'R',
        (char)SeIconChar.BoxedLetterS => 'S',
        (char)SeIconChar.BoxedLetterT => 'T',
        (char)SeIconChar.BoxedLetterU => 'U',
        (char)SeIconChar.BoxedLetterV => 'V',
        (char)SeIconChar.BoxedLetterW => 'W',
        (char)SeIconChar.BoxedLetterX => 'X',
        (char)SeIconChar.BoxedLetterY => 'Y',
        (char)SeIconChar.BoxedLetterZ => 'Z',
        _ => seIconChar
    };

    public static int? ReplaceSeIconNumbers(this char seIconChar) => seIconChar switch {
        (char)SeIconChar.BoxedNumber0 => 0,
        (char)SeIconChar.BoxedNumber1 => 1,
        (char)SeIconChar.BoxedNumber2 => 2,
        (char)SeIconChar.BoxedNumber3 => 3,
        (char)SeIconChar.BoxedNumber4 => 4,
        (char)SeIconChar.BoxedNumber5 => 5,
        (char)SeIconChar.BoxedNumber6 => 6,
        (char)SeIconChar.BoxedNumber7 => 7,
        (char)SeIconChar.BoxedNumber8 => 8,
        (char)SeIconChar.BoxedNumber9 => 9,
        (char)SeIconChar.BoxedNumber10 => 10,
        (char)SeIconChar.BoxedNumber11 => 11,
        (char)SeIconChar.BoxedNumber12 => 12,
        (char)SeIconChar.BoxedNumber13 => 13,
        (char)SeIconChar.BoxedNumber14 => 14,
        (char)SeIconChar.BoxedNumber15 => 15,
        (char)SeIconChar.BoxedNumber16 => 16,
        (char)SeIconChar.BoxedNumber17 => 17,
        (char)SeIconChar.BoxedNumber18 => 18,
        (char)SeIconChar.BoxedNumber19 => 19,
        (char)SeIconChar.BoxedNumber20 => 20,
        (char)SeIconChar.BoxedNumber21 => 21,
        (char)SeIconChar.BoxedNumber22 => 22,
        (char)SeIconChar.BoxedNumber23 => 23,
        (char)SeIconChar.BoxedNumber24 => 24,
        (char)SeIconChar.BoxedNumber25 => 25,
        (char)SeIconChar.BoxedNumber26 => 26,
        (char)SeIconChar.BoxedNumber27 => 27,
        (char)SeIconChar.BoxedNumber28 => 28,
        (char)SeIconChar.BoxedNumber29 => 29,
        (char)SeIconChar.BoxedNumber30 => 30,
        (char)SeIconChar.BoxedNumber31 => 31,
        (char)SeIconChar.Number0 => 0,
        (char)SeIconChar.Number1 => 1,
        (char)SeIconChar.Number2 => 2,
        (char)SeIconChar.Number3 => 3,
        (char)SeIconChar.Number4 => 4,
        (char)SeIconChar.Number5 => 5,
        (char)SeIconChar.Number6 => 6,
        (char)SeIconChar.Number7 => 7,
        (char)SeIconChar.Number8 => 8,
        (char)SeIconChar.Number9 => 9,
        (char)SeIconChar.BoxedOutlinedNumber0 => 0,
        (char)SeIconChar.BoxedOutlinedNumber1 => 1,
        (char)SeIconChar.BoxedOutlinedNumber2 => 2,
        (char)SeIconChar.BoxedOutlinedNumber3 => 3,
        (char)SeIconChar.BoxedOutlinedNumber4 => 4,
        (char)SeIconChar.BoxedOutlinedNumber5 => 5,
        (char)SeIconChar.BoxedOutlinedNumber6 => 6,
        (char)SeIconChar.BoxedOutlinedNumber7 => 7,
        (char)SeIconChar.BoxedOutlinedNumber8 => 8,
        (char)SeIconChar.BoxedOutlinedNumber9 => 9,
        (char)SeIconChar.Instance1 => 1,
        (char)SeIconChar.Instance2 => 2,
        (char)SeIconChar.Instance3 => 3,
        (char)SeIconChar.Instance4 => 4,
        (char)SeIconChar.Instance5 => 5,
        (char)SeIconChar.Instance6 => 6,
        (char)SeIconChar.Instance7 => 7,
        (char)SeIconChar.Instance8 => 8,
        (char)SeIconChar.Instance9 => 9,
        _ => null
    };

    public static int? ReplaceSeIconInstanceNumber(this char seIconChar) {
        return seIconChar switch {
            (char)SeIconChar.Instance1 => 1,
            (char)SeIconChar.Instance2 => 2,
            (char)SeIconChar.Instance3 => 3,
            (char)SeIconChar.Instance4 => 4,
            (char)SeIconChar.Instance5 => 5,
            (char)SeIconChar.Instance6 => 6,
            (char)SeIconChar.Instance7 => 7,
            (char)SeIconChar.Instance8 => 8,
            (char)SeIconChar.Instance9 => 9,
            _ => null
        };
    }
}
